- name: Copy Join Token from Master Node
  fetch:
    src: /tmp/join_token.txt
    dest: /tmp/join_token.txt
    flat: yes
    fail_on_missing: yes
    validate_checksum: yes
  delegate_to: cluster1-controlplane01

- name: Join Controlplane Nodes to Cluster
  command: |
    kubeadm join \
    --token="{{ lookup('file', '/tmp/join_token.txt') }}" \
    --discovery-token-ca-cert-hash="{{ lookup('file', '/tmp/discovery_token_ca_cert_hash.txt') }}" \
    --control-plane \
    --certificate-key="{{ lookup('file', '/tmp/certificate_key.txt') }}"
  delegate_to: "{{ groups['controlplane'][0] }}"

- name: Check nodes are ready
  shell: kubectl get nodes | grep -i ' Ready'
  register: result
  until: result.stdout
  retries: 20
  delay: 30

- name: Show the Kubernetes nodes
  command: kubectl get nodes
  register: result

- name: Debug the output
  debug:
    var: result.stdout_lines
        

